imports:
- { resource: parameters.yml }
- { resource: security.yml }
- { resource: services.yml }
- { resource: "@MaParcelleDeBonheurBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating: { engines: ['twig'] }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: MaParcelleDeBonheurBundle\Entity\User
    from_email:
        address: "mathieu.lacoste@lapiscine.pro"
        sender_name: "Mathieu Lacoste"

easy_admin:
    entities:
        Articles:
            class: MaParcelleDeBonheurBundle\Entity\Articles
            list:
                fields: [ {property: 'title', label: 'Titre'},
                          'date',
                          {property: 'content', label: 'Contenu', type: 'raw'}]
            show:
                title: 'Articles'
                fields: [ {property: 'title', label: 'Titre'},
                          'date',
                          {property: 'content', label: 'Contenu', type: 'raw'}]
            edit:
                title: 'Articles'
                fields: [ {property: 'title', label: 'Titre'},
                          {property: 'date', help: 'Titre 4, Police en 18, en gras et texte avec Police en 16'}
                          {property: 'content', label: 'Contenu'}]
            form:
                fields: [ {property: 'title', label: 'Titre'},
                          {property: 'date', help: 'Titre 4, Police en 18, en gras et texte avec Police en 16'}
                          {property: 'content', label: 'Contenu', type: 'ckeditor'}]
        Locataires:
            class: MaParcelleDeBonheurBundle\Entity\Locataires
            list:
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'mail', label: 'Adresse Mail'},
                          {property: 'phonenumber', label: 'Téléphone', format: '0%u'}
                          {property: 'adress', label: 'Adresse'},
                          {property: 'postalCode', label: 'Code Postal', format: '%u'},
                          {property: 'city', label: 'Ville'},
                          {property: 'parcelles', label: 'Parcelle(s)'}]
            show:
                title: 'Locataires'
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'mail', label: 'Adresse Mail'},
                          {property: 'phonenumber', label: 'Téléphone', format: '0%u'}
                          {property: 'adress', label: 'Adresse'},
                          {property: 'postalCode', label: 'Code Postal', format: '%u'},
                          {property: 'city', label: 'Ville'},
                          {property: 'parcelles', label: 'Parcelle(s)'}]
            edit:
                title: 'Locataires'
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'mail', label: 'Adresse Mail'},
                          {property: 'phonenumber', label: 'Téléphone', format: '0%u', help: "Ne pas mettre le 0"}
                          {property: 'adress', label: 'Adresse'},
                          {property: 'postalCode', label: 'Code Postal', format: '%u'},
                          {property: 'city', label: 'Ville'},
                          {property: 'parcelles', label: 'Parcelle(s)', help: "ATTENTION, Passer par l'onglet Parcelles pour l'attribution"}]
            form:
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'mail', label: 'Adresse Mail'},
                          {property: 'phonenumber', label: 'Téléphone', format: '0%u'}
                          {property: 'adress', label: 'Adresse'},
                          {property: 'postalCode', label: 'Code Postal', format: '%u'},
                          {property: 'city', label: 'Ville'},
                          {property: 'parcelles', label: 'Parcelle(s)', help: "ATTENTION, Passer par l'onglet Parcelles pour l'attribution"}]
        Parcelles:
            class: MaParcelleDeBonheurBundle\Entity\Parcelles
            list:
                fields: [ {property: 'matricule', label: 'Matricule'},
                          {property: 'street', label: 'Allée'},
                          {property: 'number', label: 'Numéro'},
                          {property: 'area', label: 'Superficie (m2)'},
                          {property: 'locataires', label: 'Locataire'}]
            show:
                title: 'Parcelles'
                fields: [ {property: 'matricule', label: 'Matricule'},
                          {property: 'street', label: 'Allée'},
                          {property: 'number', label: 'Numéro'},
                          {property: 'area', label: 'Superficie (m2)'},
                          {property: 'locataires', label: 'Locataire'}]
            edit:
                title: 'Parcelles'
                fields: [ {property: 'matricule', label: 'Matricule'},
                          {property: 'street', label: 'Allée'},
                          {property: 'number', label: 'Numéro'},
                          {property: 'area', label: 'Superficie (m2)'},
                          {property: 'locataires', label: 'Locataire'}]
            form:
                fields: [ {property: 'matricule', label: 'Matricule'},
                          {property: 'street', label: 'Allée'},
                          {property: 'number', label: 'Numéro'},
                          {property: 'area', label: 'Superficie (m2)'},
                          {property: 'locataires', label: 'Locataire'}]
        Contact:
            class: MaParcelleDeBonheurBundle\Entity\Contact
            label: 'Messages'
            list:
                title: 'Messages reçus via le site'
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'subject', label: 'Sujet'},
                          {property: 'message', label: 'Message'}]
            show:
                title: 'Messages reçus via le site'
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'subject', label: 'Sujet'},
                          {property: 'mail', label: 'Adresse Mail'},
                          {property: 'phonenumber', label: 'Numéro', format: '0%u'},
                          {property: 'message', label: 'Message'}]
            edit:
                title: 'Messages reçus via le site'
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'subject', label: 'Sujet'},
                          {property: 'message', label: 'Message'}]
            form:
                fields: [ {property: 'name', label: 'Nom'},
                          {property: 'firstname', label: 'Prénom'},
                          {property: 'subject', label: 'Sujet'},
                          {property: 'message', label: 'Message'}]
        User:
            class: MaParcelleDeBonheurBundle\Entity\User
            label: 'Administrateurs'
            list:
                title: 'Administrateurs du Site'
                fields: [ {property: 'username', label: 'Identifiant'},
                          {property: 'email', label: 'Email'},
                          {property: 'enabled', label: 'Autorisé'},
                          {property: 'roles', label: 'Type Administrateur'},
                          {property: 'lastLogin', label: 'Dernière Connexion'}]

    design:
        brand_color: '#0ba660'
        assets:
            favicon: 'assets/images/favicons/favicon.png'

    show:
        max_results: 30

    list:
        actions: ['show']

ivory_ck_editor:
    configs:
        my_config:
            toolbar: full
            uiColor: '#0ba660'