<?php

namespace MaParcelleDeBonheurBundle\Repository;

/**
 * Articles
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Articles extends \Doctrine\ORM\EntityRepository
{
}
