<?php

namespace MaParcelleDeBonheurBundle\Repository;

/**
 * Contact
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Contact extends \Doctrine\ORM\EntityRepository
{
}
