<?php

namespace MaParcelleDeBonheurBundle\Repository;

/**
 * Locataires
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Locataires extends \Doctrine\ORM\EntityRepository
{
}
