<?php

namespace MaParcelleDeBonheurBundle\Repository;

/**
 * Parcelles
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Parcelles extends \Doctrine\ORM\EntityRepository
{
}
